# Generated by Django 5.2.8 on 2025-11-22 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('created_at', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='идентификатор пользователя')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('created_at', models.DateTimeField(verbose_name='дата публикации')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.questions')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
